# Generated by Django 4.2.11 on 2025-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
